version: '3.1'

services:
  mongo:
    image: mongo:4.2.23
    environment:
      - MONGO_INITDB_DATABASE=house
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '${MONGO_INITDB_ROOT_PORT}:27017'
    volumes:
      - ./data:/data/db
